package com.llama.petmilly_client.presentation.shelterWrite

enum class ShelterRoute(
    val route: String
) {
    SHELTER_WRITE_PET_INFO("SHELTER_WRITE_PET_INFO"),
    SHELTER_WRITE_PROFILE("SHELTER_WRITE_PROFILE"),
    SHELTER_WRITE_PROFILE_DETAIL_INFO("SHELTER_WRITE_PROFILE_DETAIL_INFO"),
    SHELTER_WRITE_PROFILE_THIRD("SHELTER_WRITE_PROFILE_THIRD"),
    SHELTER_WRITE_PROFILE_LAST("SHELTER_WRITE_PROFILE_LAST"),
    SHELTER_WRITE_CONDITION("SHELTER_WRITE_CONDITION"),
    SHELTER_WRITE_CONDITION_LAST("SHELTER_WRITE_CONDITION_LAST"),
    SHELTER_WRITE_CHARM_APPEAL("SHELTER_WRITE_CHARM_APPEAL"),
    SHELTER_WRITE_APPLICATION_PERIOD("SHELTER_WRITE_APPLICATION_PERIOD")
}
